//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket_Products
    {
        public int ID { get; set; }
        public int IDProduct { get; set; }
        public int CountProd { get; set; }
        public int IdUser { get; set; }
    
        public virtual BasketOfGoods BasketOfGoods { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
