//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class defects_parts
    {
        public int defectID { get; set; }
        public int partID { get; set; }
        public decimal repairPrice { get; set; }
    
        public virtual defects defects { get; set; }
        public virtual Parts Parts { get; set; }
    }
}
