//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GuydaCarServiceEntities : DbContext
    {
        public GuydaCarServiceEntities()
            : base("name=GuydaCarServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cars> cars { get; set; }
        public virtual DbSet<defects> defects { get; set; }
        public virtual DbSet<defects_parts> defects_parts { get; set; }
        public virtual DbSet<Parts> Parts { get; set; }
        public virtual DbSet<parts_player> parts_player { get; set; }
        public virtual DbSet<player> player { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
