//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Warehouse
    {
        public int IDProd { get; set; }
        public int IDwarehouse { get; set; }
        public int CountProd { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
